stages:
  - deploy

pages:
  stage: deploy
  image:
    name: pandoc/latex
    entrypoint: [""]
  variables:
    OUT_DIR: public
  script:
    - ". ./make.sh"
  artifacts:
    paths:
    - public
  only:
  - master
